name: Hector's Blog
description: Hack your way out
avatar: https://avatars0.githubusercontent.com/u/3007365?s=460&v=4
github: mebjas
email: minhazav@gmail.com

copyright_year: 2019
copyright_owner: minhazav.dev
category_dir: category
url: "http://mebjas.github.io"
# repository: "mebjas/mebjas.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Includes an icon in the footer for each username you enter
footer-links:
  email: minhazav@gmail.com
  facebook:
  github: mebjas
  instagram: mebjas
  linkedin: https://www.linkedin.com/in/minhazav
  twitter: minhazav
  stackoverflow: users/2614250/mebjas

# Outputting
permalink: /:title/
timezone: Etc/UTC

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
highlighter: rouge
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  blanklines: true
  clippings: all
  comments: all

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - staticman.yml

defaults:
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# The release of Jekyll Now that you're using
# version: v3.0

category_descriptions:
  - { name: "distributed systems", description: "" }
  - { name: "hackathon", description: "" }
  - { name: "Key Value Store", description: "" }
  - { name: "node js", description: "" }
  - { name: "graphics", description: "" }
  - { name: "html Canvas", description: "" }
  - { name: "javascript", description: "" }
  - { name: "mathematics", description: "" }
